var rx=rx||{};rx.zhr=function(a,b,c){"undefined"==typeof a||"undefined"==typeof b||"undefined"==typeof c?console.log("all paramters not provided"):(this.servermethod=a,this.successcall=b);this.constructor.prototype.do=function(a){var d=new XMLHttpRequest;d.open(c,this.servermethod,!0);d.setRequestHeader("Content-type","application/json; charset\x3dutf-8");d.onreadystatechange=function(){4==d.readyState&&200==d.status&&window[b](JSON.parse(d.responseText))};"undefined"==typeof a?d.send():d.send(JSON.stringify(a))}};
var END_POINT="http://api.zest.is/";
function isMobile(){var a=!1;if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,4)))a=
!0;return a}function onInlineSuccess(){console.log("SUCCESS");ga("send","event","Install","inline-install","Inline-installation SUCCESS")}function onInlineFailed(a){}function sideNavScroll(a,b,c){var e=window.pageYOffset||document.documentElement.scrollTop;70<=e?a.classList.add("to_top"):a.classList.remove("to_top");e>=b.offsetHeight-c+80?a.classList.add("fold"):a.classList.remove("fold")}
function tilesBgScroll(a){var b=window.pageYOffset||document.documentElement.scrollTop;a.style.webkitTransform="translateY( "+Math.max(-b/3,-500)+"px)";a.style.transform="translateY( "+Math.max(-b/3,-500)+"px)"}function sendNewsletterSubscribe(){document.querySelector("#newsletter button i").className="icon-loading";(new rx.zhr(END_POINT+"subscribeNewsletter","onNewsletterSubscribeDone","POST")).do({email:document.getElementById("newsletter-subscribe").value})}
function onNewsletterSubscribeDone(a){document.querySelector("#newsletter button i").className="icon-send";document.getElementById("newsletter-subscribe").value="";0==a.code?document.getElementById("newsletter-email-success").style.display="block":document.getElementById("newsletter-email-failure").style.display="block"}
function sendMobileSubscribe(){document.querySelector("#mobile-form button i").className="icon-loading";(new rx.zhr(END_POINT+"subscriberMobile","onMobileSubscribeDone","POST")).do({email:document.getElementById("mobile-email").value})}
function onMobileSubscribeDone(a){document.querySelector("#mobile-form button i").className="icon-send";document.getElementById("mobile-email").value="";0==a.code?document.getElementById("mobile-email-success").style.display="block":document.getElementById("mobile-email-failure").style.display="block"}
function valMobileEmail(){document.getElementById("mobile-email-alert").style.display="none";document.getElementById("mobile-email-success").style.display="none";document.getElementById("mobile-email-failure").style.display="none";validateEmail(document.getElementById("mobile-email").value)?sendMobileSubscribe():setTimeout(function(){document.getElementById("mobile-email-alert").style.display="block"},0)}
function valNewsletterEmail(){document.getElementById("newsletter-email-alert").style.display="none";document.getElementById("newsletter-email-success").style.display="none";document.getElementById("newsletter-email-failure").style.display="none";validateEmail(document.getElementById("newsletter-subscribe").value)?sendNewsletterSubscribe():setTimeout(function(){document.getElementById("newsletter-email-alert").style.display="block"},0)}
function validateEmail(a){return/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(a)}
var general=function(){function a(){c.parentNode.removeChild(c)}isMobile()&&document.getElementById("wrapper")&&document.getElementById("wrapper").classList.add("touch");var b=document.getElementById("menu"),c=document.getElementById("loader"),e=document.querySelector("#tiles-bg i"),d=document.querySelector(".side-nav"),f=document.querySelector(".side-column");setTimeout(function(){c&&(c.classList.add("done"),c.addEventListener("webkitTransitionEnd",a),c.addEventListener("transitionend",a));e&&1024<
window.innerWidth&&(tilesBgScroll(e),window.addEventListener("scroll",function(){tilesBgScroll(e)}));if(d&&f&&640<window.innerWidth){var b=d.offsetHeight;sideNavScroll(d,f,b);window.addEventListener("scroll",function(){sideNavScroll(d,f,b)})}},600);document.getElementById("hamburger")&&(document.getElementById("hamburger").onclick=function(a){b.classList.toggle("active");a.stopPropagation();ga("send","event","Menu","main-menu","Main menu open")});document.getElementById("wrapper")&&(document.getElementById("wrapper").onclick=
function(){b&&b.classList.contains("active")&&(b.classList.remove("active"),ga("send","event","Menu","main-menu","Main menu close"))});document.querySelector("#mobile-form button")&&document.querySelector("#mobile-form button").addEventListener("click",function(a){a.preventDefault();valMobileEmail()},!1);document.querySelector("#newsletter button")&&document.querySelector("#newsletter button").addEventListener("click",function(a){a.preventDefault();valNewsletterEmail()},!1);var g=document.querySelectorAll(".CTA");
if(!/zest-lite/.test(location.href))for(var h=0;h<g.length;h++)g[h].addEventListener("click",function(a){chrome&&chrome.webstore&&chrome.webstore.install&&(a.preventDefault(),chrome.webstore.install("https://chrome.google.com/webstore/detail/lgbbbmmegpehafpempogpgacjnfcbekj",onInlineSuccess,onInlineFailed));a="Hero";this.classList.contains("in-footer")&&(a="Footer");this.classList.contains("in-menu")&&(a="Menu");ga("send","event","CTA-click","click","CTA in "+a+" clicked")},!1);document.getElementById("flag-form")&&
document.getElementById("flag-form").addEventListener("submit",sendFlagMessage,!1);document.getElementById("uninstall-form")&&document.getElementById("uninstall-form").addEventListener("submit",sendUninstall,!1);document.getElementById("contact-form")&&document.getElementById("contact-form").addEventListener("submit",sendContactMessage,!1)};
function sendContactMessage(a){a.preventDefault();toggleContactFormAlerts("none","none");a={};for(var b=this.getElementsByTagName("input"),c=0;c<b.length;c++)a[b[c].getAttribute("name")]=b[c].value;b=this.getElementsByTagName("textarea")[0];a[b.getAttribute("name")]=b.value;(new rx.zhr(END_POINT+"contact","onContactDone","POST")).do(a)}
function sendFlagMessage(a){a.preventDefault();toggleContactFormAlerts("none","none");a={};for(var b=this.getElementsByTagName("input"),c=0;c<b.length;c++)a[b[c].getAttribute("name")]=b[c].value;b=this.getElementsByTagName("textarea")[0];a[b.getAttribute("name")]=b.value;(new rx.zhr(END_POINT+"sendReport","onSendFlagDone","POST")).do(a)}
function sendUninstall(a){a.preventDefault();toggleContactFormAlerts("none","none");a={};for(var b=this.getElementsByTagName("input"),c=0;c<b.length;c++)a[b[c].getAttribute("name")]=b[c].value;b=this.getElementsByTagName("select")[0];a[b.getAttribute("name")]=b.value;b=this.getElementsByTagName("textarea")[0];a[b.getAttribute("name")]=b.value;(new rx.zhr(END_POINT+"uninstall","onUninstallDone","POST")).do(a)}
function toggleContactFormAlerts(a,b){document.getElementById("contact-failure").style.display=a;document.getElementById("contact-success").style.display=b;"none"==a&&"none"==b&&(document.querySelector(".contact-page-form button i").className="icon-loading")}
function contactResponse(a){document.querySelector(".contact-page-form button i").className="icon-send";0==a.code?(toggleContactFormAlerts("none","block"),document.querySelector(".contact-page-form textarea").value="",document.querySelectorAll(".contact-page-form input").forEach(function(a){a.value=""})):toggleContactFormAlerts("block","none")}function onSendFlagDone(a){contactResponse(a)}function onUninstallDone(a){contactResponse(a)}function onContactDone(a){contactResponse(a)}
function createCookie(a,b,c){var e="";c&&(e=new Date,e.setTime(e.getTime()+864E5*c),e="; expires\x3d"+e.toGMTString());document.cookie=a+"\x3d"+b+e+"; path\x3d/"}"loading"!=document.readyState?general():document.addEventListener("DOMContentLoaded",general);
(function(a,b,c,e,d,f,g){a.GoogleAnalyticsObject=d;a[d]=a[d]||function(){(a[d].q=a[d].q||[]).push(arguments)};a[d].l=1*new Date;f=b.createElement(c);g=b.getElementsByTagName(c)[0];f.async=1;f.src=e;g.parentNode.insertBefore(f,g)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create","UA-69774312-1","auto");ga("send","pageview");